package proyecto_sev1;
import clases.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.util.*;
import java.awt.event.*;
public class administrador extends JFrameConFondo {
    /** Creates new form administrador */
    public administrador() {
        initComponents();
         this.setTitle("ADMINISTRADOR");//codigo para titulo en ventana
        setImagen("Recursos/actualizarInfo.jpg");//codigo para imagen en Panel
        setLocationRelativeTo(null);// para que la ventana este siempre centrada
        Reloj modelo=new Reloj();//codigo para crear objeto de clase Reloj
                modelo.addObserver (new Observer()
                 {
                     public void update (Observable unObservable, Object dato)
                     {
                         jLbl_reloj.setText(""+dato);//codigo para mostrar reloj
                     }
                 });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbl_usuario = new javax.swing.JLabel();
        jLbl_codigo = new javax.swing.JLabel();
        jPasswordFld_codigo = new javax.swing.JPasswordField();
        jBtn_ir_editar = new javax.swing.JButton();
        jBtn_ir_NewJFrame = new javax.swing.JButton();
        jLel_mensaje = new javax.swing.JLabel();
        jTxFld_admin = new javax.swing.JTextField();
        jLbl_reloj = new javax.swing.JLabel();
        jLbl_imagenHerramientas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLbl_usuario.setForeground(new java.awt.Color(102, 0, 102));
        jLbl_usuario.setText("USUARIO:");
        jLbl_usuario.setName("jLbl_usuario"); // NOI18N

        jLbl_codigo.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLbl_codigo.setForeground(new java.awt.Color(102, 0, 102));
        jLbl_codigo.setText("CONTRASEÑA:");
        jLbl_codigo.setName("jLbl_codigo"); // NOI18N

        jPasswordFld_codigo.setForeground(new java.awt.Color(102, 0, 102));
        jPasswordFld_codigo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 102)));
        jPasswordFld_codigo.setName("jPasswordFld_codigo"); // NOI18N

        jBtn_ir_editar.setFont(new java.awt.Font("Tahoma", 1, 12));
        jBtn_ir_editar.setForeground(new java.awt.Color(0, 0, 153));
        jBtn_ir_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/hg.JPG"))); // NOI18N
        jBtn_ir_editar.setText(" ACEPTAR");
        jBtn_ir_editar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 0, 102)));
        jBtn_ir_editar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jBtn_ir_editar.setName("jBtn_ir_editar"); // NOI18N
        jBtn_ir_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_ir_editarMouseClicked(evt);
            }
        });

        jBtn_ir_NewJFrame.setFont(new java.awt.Font("Tahoma", 1, 12));
        jBtn_ir_NewJFrame.setForeground(new java.awt.Color(0, 0, 153));
        jBtn_ir_NewJFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/hvfk.JPG"))); // NOI18N
        jBtn_ir_NewJFrame.setText("  SALIR   ");
        jBtn_ir_NewJFrame.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 0, 102)));
        jBtn_ir_NewJFrame.setName("jBtn_ir_NewJFrame"); // NOI18N
        jBtn_ir_NewJFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_ir_NewJFrameMouseClicked(evt);
            }
        });

        jLel_mensaje.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLel_mensaje.setForeground(new java.awt.Color(153, 0, 0));
        jLel_mensaje.setName("jLel_mensaje"); // NOI18N

        jTxFld_admin.setEditable(false);
        jTxFld_admin.setForeground(new java.awt.Color(102, 0, 102));
        jTxFld_admin.setText("ADMIN");
        jTxFld_admin.setName("jTxFld_admin"); // NOI18N

        jLbl_reloj.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLbl_reloj.setForeground(new java.awt.Color(51, 0, 102));
        jLbl_reloj.setName("jLbl_reloj"); // NOI18N

        jLbl_imagenHerramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/herramienta.jpg"))); // NOI18N
        jLbl_imagenHerramientas.setName("jLbl_imagenHerramientas"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLbl_usuario)
                                .addGap(44, 44, 44)
                                .addComponent(jTxFld_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbl_codigo)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordFld_codigo)))
                        .addGap(18, 18, 18)
                        .addComponent(jLbl_imagenHerramientas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLel_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_reloj, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jBtn_ir_NewJFrame)
                .addGap(18, 18, 18)
                .addComponent(jBtn_ir_editar)
                .addGap(27, 27, 27))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtn_ir_NewJFrame, jBtn_ir_editar});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPasswordFld_codigo, jTxFld_admin});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxFld_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_usuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_codigo)
                            .addComponent(jPasswordFld_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLbl_imagenHerramientas, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLel_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLbl_reloj, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_ir_NewJFrame)
                    .addComponent(jBtn_ir_editar))
                .addGap(22, 22, 22))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtn_ir_NewJFrame, jBtn_ir_editar});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPasswordFld_codigo, jTxFld_admin});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLbl_reloj, jLel_mensaje});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_ir_NewJFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_ir_NewJFrameMouseClicked
        // TODO add your handling code here:
        NewJFrame ir = new  NewJFrame();// crea objeto para ir a nueva ventana
        this.setVisible(false);//oculta la ventana actual
        ir.setVisible(true);//muestra la nueva ventana
        ir.setLocationRelativeTo(null);// para que la ventana este siempre centrada
    }//GEN-LAST:event_jBtn_ir_NewJFrameMouseClicked

    private void jBtn_ir_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_ir_editarMouseClicked

        try {
            // TODO add your handling code here:
            String contra = jPasswordFld_codigo.getText(); //captura el numero de CI
            File archivo = null;
            FileReader fr = null;
            BufferedReader br = null;
            // Apertura del fichero y creacion de BufferedReader para poder
            // hacer una lectura comoda (disponer del metodo readLine()) para
            // poder verificar la contraseña ingresada
            archivo = new File("administrador.txt");
            fr = new FileReader(archivo);
            br = new BufferedReader(fr);
            // Lectura del fichero
            String linea;
            while ((linea = br.readLine()) != null) //guarda el contenido de cada linea de fichero hasta el final y guarda en linea
            {
                if (contra.equals(linea)) {
                    editar ir = new editar(); // crea objeto para ir a nueva ventana
                    this.setVisible(false); //oculta la ventana actual
                    ir.setVisible(true); //muestra la nueva ventana
                    ir.setLocationRelativeTo(null); // para que la ventana este siempre centrada
                } else // cuando contraseña ingresada sea incorrecta
                {
                    jLel_mensaje.setText("CONTRASEÑA INCORRECTA"); //muestra mensaje si la contraseña es incorrecta
                    jPasswordFld_codigo.setText(""); //limpia PasswordField para ingresar de nuevo la contraseña
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(administrador.class.getName()).log(Level.SEVERE, null, ex);
        } 
          
             

    }//GEN-LAST:event_jBtn_ir_editarMouseClicked

    /**
    * @param args the command line arguments
    */
   
//public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//
//                    new administrador().setVisible(true); // clase principal
//
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_ir_NewJFrame;
    private javax.swing.JButton jBtn_ir_editar;
    private javax.swing.JLabel jLbl_codigo;
    private javax.swing.JLabel jLbl_imagenHerramientas;
    private javax.swing.JLabel jLbl_reloj;
    private javax.swing.JLabel jLbl_usuario;
    private javax.swing.JLabel jLel_mensaje;
    private javax.swing.JPasswordField jPasswordFld_codigo;
    private javax.swing.JTextField jTxFld_admin;
    // End of variables declaration//GEN-END:variables

}
