package proyecto_sev1;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
public class ImprimeCertificadoVotos extends JFrameConFondo {
    public void ingresarTexto(String texto) {
        jTxtA_ImprimeCertificado.setText(texto);
    }
    /** Creates new form ImprimeCertificadoVotos */
    public ImprimeCertificadoVotos() {
        initComponents();
        setLocationRelativeTo(null);// //codigo para que la ventana este siempre centrada
        setImagen("Recursos/bandera.jpg");//codigo para imagen en Panel
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtA_ImprimeCertificado = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTxtA_ImprimeCertificado.setColumns(20);
        jTxtA_ImprimeCertificado.setRows(5);
        jTxtA_ImprimeCertificado.setName("jTxtA_ImprimeCertificado"); // NOI18N
        jTxtA_ImprimeCertificado.setSelectionColor(new java.awt.Color(102, 102, 0));
        jScrollPane1.setViewportView(jTxtA_ImprimeCertificado);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/imprimir.jpg"))); // NOI18N
        jButton1.setText("IMPRIMIR");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 102)));
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("CERTIFICADO DE VOTACION");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            // TODO add your handling code here:
            // crea objeto para ir a nueva ventana
            votantes ir = new votantes(); // crea objeto para ir a nueva ventana
            this.setVisible(false); //oculta la ventana actual
            ir.setVisible(true); // para que la ventana este siempre centrada
            ir.setLocationRelativeTo(null); // para que la ventana este siempre centrada
            String family = "Serif";
            int style = Font.ROMAN_BASELINE;
            int size = 20;
            Font fuente = new Font(family, style, size);
            //Terminacion de fuente
            Properties defaultProps = new Properties();
            PrintJob print = Toolkit.getDefaultToolkit().getPrintJob(this, "Imprimir", defaultProps);
            Graphics g = null;
            if (print != null) {
                g = print.getGraphics();
            }
            if (g != null) {
                jTxtA_ImprimeCertificado.printAll(g);
                g.dispose();
                print.end();
            }
        }
        /**
         * @param args the command line arguments
         */ catch (FileNotFoundException ex) {
            Logger.getLogger(ImprimeCertificadoVotos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ImprimeCertificadoVotos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtA_ImprimeCertificado;
    // End of variables declaration//GEN-END:variables
}
