package proyecto_sev1;
import clases.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.io.*;
import java.util.*;
import java.awt.event.*;
public class papeleta_diputados_alcaldes extends JFrameConFondo {
    private ImprimeCertificadoVotos imprimir = new ImprimeCertificadoVotos();

    /** Creates new form papeleta_diputados_alcaldes */
    public papeleta_diputados_alcaldes() throws FileNotFoundException, IOException {
        initComponents();
        setImagen("Recursos/blanco.jpg");//codigo para imagen en Panel
        setLocationRelativeTo(null);// para que la ventana este siempre centrada
        Reloj modelo=new Reloj();//codigo para crear objeto de clase Reloj
                modelo.addObserver (new Observer()
                 {
                     public void update (Observable unObservable, Object dato)
                     {
                         jLbl_reloj.setText(""+dato);//codigo para mostrar reloj
                     }
                 });
                  // codigo para mostrar los datos de la persona que esta votando
           File archivo = null;
           FileReader fr = null;
           BufferedReader br = null;
           archivo = new File ("Compararcedula.txt");//abre fichero para verificar que la persona este empadronada y pueda votar solo una vez
           fr = new FileReader (archivo);
           br = new BufferedReader(fr);
           String linea="";//inicializa linea para poder leer linea de fichero
           while((linea=br.readLine())!=null)//hace la comparacion hasta que exista linea en blanco
             {
                jLbl_CIPersonal.setText(""+linea);//muestra la CI de la persona que esta votando
            }
           String cedula1=(String)jLbl_CIPersonal.getText();//guarda la cedula de identidad de la persona que vota
        buscar busempa = new buscar("empa.txt");//llamada a clase buscar
        String datos = busempa.BuscarDatos(cedula1);//llamada a metodo BuscarDatos de clase buscar //verifica que exista la cedula ingresada este fichero
        if (datos.equals("")){//verifica que exista cedula
            JOptionPane.showMessageDialog(null,"NO ESTA EMPADRONADO","  ERROR",0);//mensaje de no existe
        }
        else
        {
            StringTokenizer tok = new StringTokenizer(datos,"\t");//codigo para poder leer cada dato de empadronado
            tok.nextToken();//salta al siguiente dato de empadronado
            String codigo = tok.nextToken().toString();//guarda codigo de empadronado
            String nombre = tok.nextToken().toString();//guarda nombre de fichero
            String apellido = tok.nextToken().toString();//guarda apellido de fichero
            jLbl_codigoPersonal.setText(codigo);//muestra codigo de empadronado
            jLbl_nombrePersonal.setText( nombre);//muestra nombre de empadronado
            jLbl_apellidoPersonal.setText(apellido);//muestra apellido de empadronado
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbl_titulo_listaDiputadosAlcaldes = new javax.swing.JLabel();
        jPnl_diputados = new javax.swing.JPanel();
        jPnl_diputadoCorrea = new javax.swing.JPanel();
        jLbl_imagenDiputado1 = new javax.swing.JLabel();
        jRdBtn_nombreDiputado1 = new javax.swing.JRadioButton();
        jPnl_diputadoGutierrez = new javax.swing.JPanel();
        jLbl_imagenDiputado2 = new javax.swing.JLabel();
        jRdBtn_nombreDiputado2 = new javax.swing.JRadioButton();
        jPnl_diputadoMahuad = new javax.swing.JPanel();
        jLbl_imagenDiputado3 = new javax.swing.JLabel();
        jRdBtn_nombreDiputado3 = new javax.swing.JRadioButton();
        jPnl_diputadoRoldos = new javax.swing.JPanel();
        jLbl_imagenDiputado4 = new javax.swing.JLabel();
        jRdBtn_nombreDiputado4 = new javax.swing.JRadioButton();
        jPnl_alcaldes = new javax.swing.JPanel();
        jPnl_alcaldeCorrea = new javax.swing.JPanel();
        jLbl_imagenAlcalde1 = new javax.swing.JLabel();
        jRdBtn_nombreAlcalde1 = new javax.swing.JRadioButton();
        jPnl_alcaldeGutierrez = new javax.swing.JPanel();
        jLbl_imagenAlcalde2 = new javax.swing.JLabel();
        jRdBtn_nombreAlcalde2 = new javax.swing.JRadioButton();
        jPnl_alcaldeMahuad = new javax.swing.JPanel();
        jLbl_imagenAlcalde3 = new javax.swing.JLabel();
        jRdBtn_nombreAlcalde3 = new javax.swing.JRadioButton();
        jPnl_alcaldeRoldos = new javax.swing.JPanel();
        jLbl_imagenAlcalde4 = new javax.swing.JLabel();
        jRdBtn_nombreAlcalde4 = new javax.swing.JRadioButton();
        jBtn_ir_votantes = new javax.swing.JButton();
        jLbl_reloj = new javax.swing.JLabel();
        jPnl_datosPersonales = new javax.swing.JPanel();
        jLbl_apellido = new javax.swing.JLabel();
        jLbl_nombre = new javax.swing.JLabel();
        jLbl_apellidoPersonal = new javax.swing.JLabel();
        jLbl_nombrePersonal = new javax.swing.JLabel();
        jLbl_CI = new javax.swing.JLabel();
        jLbl_CIPersonal = new javax.swing.JLabel();
        jLbl_codigo = new javax.swing.JLabel();
        jLbl_codigoPersonal = new javax.swing.JLabel();
        jLbl_gifmuñeco = new javax.swing.JLabel();
        jLbl_gifmapa = new javax.swing.JLabel();
        jLbl_imagenmuñeco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLbl_titulo_listaDiputadosAlcaldes.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLbl_titulo_listaDiputadosAlcaldes.setForeground(new java.awt.Color(51, 0, 102));
        jLbl_titulo_listaDiputadosAlcaldes.setText("LISTA DE DIPUTADOS - ALCALDES");
        jLbl_titulo_listaDiputadosAlcaldes.setName("jLbl_titulo_listaDiputadosAlcaldes"); // NOI18N

        jPnl_diputados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DIPUTADOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 102))); // NOI18N
        jPnl_diputados.setName("jPnl_diputados"); // NOI18N

        jPnl_diputadoCorrea.setBackground(new java.awt.Color(255, 255, 255));
        jPnl_diputadoCorrea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eco. Rafael Correa", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(51, 0, 102))); // NOI18N
        jPnl_diputadoCorrea.setName("jPnl_diputadoCorrea"); // NOI18N

        jLbl_imagenDiputado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/candidato1.JPG"))); // NOI18N
        jLbl_imagenDiputado1.setName("jLbl_imagenDiputado1"); // NOI18N

        jRdBtn_nombreDiputado1.setFont(new java.awt.Font("Tahoma", 1, 10));
        jRdBtn_nombreDiputado1.setForeground(new java.awt.Color(51, 0, 102));
        jRdBtn_nombreDiputado1.setText("Ab. Roberto Salas ");
        jRdBtn_nombreDiputado1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 102)));
        jRdBtn_nombreDiputado1.setName("jRdBtn_nombreDiputado1"); // NOI18N
        jRdBtn_nombreDiputado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdBtn_nombreDiputado1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnl_diputadoCorreaLayout = new javax.swing.GroupLayout(jPnl_diputadoCorrea);
        jPnl_diputadoCorrea.setLayout(jPnl_diputadoCorreaLayout);
        jPnl_diputadoCorreaLayout.setHorizontalGroup(
            jPnl_diputadoCorreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_diputadoCorreaLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jRdBtn_nombreDiputado1)
                .addContainerGap())
            .addGroup(jPnl_diputadoCorreaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLbl_imagenDiputado1)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPnl_diputadoCorreaLayout.setVerticalGroup(
            jPnl_diputadoCorreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_diputadoCorreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbl_imagenDiputado1)
                .addGap(18, 18, 18)
                .addComponent(jRdBtn_nombreDiputado1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPnl_diputadoGutierrez.setBackground(new java.awt.Color(255, 255, 255));
        jPnl_diputadoGutierrez.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crnl. Lucio Gutierrez", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(51, 0, 102))); // NOI18N
        jPnl_diputadoGutierrez.setName("jPnl_diputadoGutierrez"); // NOI18N

        jLbl_imagenDiputado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/candidato2.JPG"))); // NOI18N
        jLbl_imagenDiputado2.setName("jLbl_imagenDiputado2"); // NOI18N

        jRdBtn_nombreDiputado2.setFont(new java.awt.Font("Tahoma", 1, 10));
        jRdBtn_nombreDiputado2.setForeground(new java.awt.Color(51, 0, 102));
        jRdBtn_nombreDiputado2.setText("Gnrl. Antonio Torres ");
        jRdBtn_nombreDiputado2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 102)));
        jRdBtn_nombreDiputado2.setName("jRdBtn_nombreDiputado2"); // NOI18N

        javax.swing.GroupLayout jPnl_diputadoGutierrezLayout = new javax.swing.GroupLayout(jPnl_diputadoGutierrez);
        jPnl_diputadoGutierrez.setLayout(jPnl_diputadoGutierrezLayout);
        jPnl_diputadoGutierrezLayout.setHorizontalGroup(
            jPnl_diputadoGutierrezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_diputadoGutierrezLayout.createSequentialGroup()
                .addGroup(jPnl_diputadoGutierrezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRdBtn_nombreDiputado2)
                    .addGroup(jPnl_diputadoGutierrezLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLbl_imagenDiputado2)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPnl_diputadoGutierrezLayout.setVerticalGroup(
            jPnl_diputadoGutierrezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_diputadoGutierrezLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbl_imagenDiputado2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jRdBtn_nombreDiputado2)
                .addContainerGap())
        );

        jPnl_diputadoMahuad.setBackground(new java.awt.Color(255, 255, 255));
        jPnl_diputadoMahuad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dr. Jamil Mahuad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(51, 0, 102))); // NOI18N
        jPnl_diputadoMahuad.setName("jPnl_diputadoMahuad"); // NOI18N

        jLbl_imagenDiputado3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/candidato3.JPG"))); // NOI18N
        jLbl_imagenDiputado3.setName("jLbl_imagenDiputado3"); // NOI18N

        jRdBtn_nombreDiputado3.setFont(new java.awt.Font("Tahoma", 1, 10));
        jRdBtn_nombreDiputado3.setForeground(new java.awt.Color(51, 0, 102));
        jRdBtn_nombreDiputado3.setText("Ing. Cristina Robles");
        jRdBtn_nombreDiputado3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 102)));
        jRdBtn_nombreDiputado3.setName("jRdBtn_nombreDiputado3"); // NOI18N

        javax.swing.GroupLayout jPnl_diputadoMahuadLayout = new javax.swing.GroupLayout(jPnl_diputadoMahuad);
        jPnl_diputadoMahuad.setLayout(jPnl_diputadoMahuadLayout);
        jPnl_diputadoMahuadLayout.setHorizontalGroup(
            jPnl_diputadoMahuadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_diputadoMahuadLayout.createSequentialGroup()
                .addGroup(jPnl_diputadoMahuadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnl_diputadoMahuadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRdBtn_nombreDiputado3))
                    .addGroup(jPnl_diputadoMahuadLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLbl_imagenDiputado3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnl_diputadoMahuadLayout.setVerticalGroup(
            jPnl_diputadoMahuadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_diputadoMahuadLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLbl_imagenDiputado3)
                .addGap(18, 18, 18)
                .addComponent(jRdBtn_nombreDiputado3)
                .addContainerGap())
        );

        jPnl_diputadoRoldos.setBackground(new java.awt.Color(255, 255, 255));
        jPnl_diputadoRoldos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ab. Jaime Roldos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(51, 0, 102))); // NOI18N
        jPnl_diputadoRoldos.setName("jPnl_diputadoRoldos"); // NOI18N

        jLbl_imagenDiputado4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/candidato4.JPG"))); // NOI18N
        jLbl_imagenDiputado4.setName("jLbl_imagenDiputado4"); // NOI18N

        jRdBtn_nombreDiputado4.setFont(new java.awt.Font("Tahoma", 1, 10));
        jRdBtn_nombreDiputado4.setForeground(new java.awt.Color(51, 0, 102));
        jRdBtn_nombreDiputado4.setText("Arq. David Beckan");
        jRdBtn_nombreDiputado4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 102)));
        jRdBtn_nombreDiputado4.setName("jRdBtn_nombreDiputado4"); // NOI18N

        javax.swing.GroupLayout jPnl_diputadoRoldosLayout = new javax.swing.GroupLayout(jPnl_diputadoRoldos);
        jPnl_diputadoRoldos.setLayout(jPnl_diputadoRoldosLayout);
        jPnl_diputadoRoldosLayout.setHorizontalGroup(
            jPnl_diputadoRoldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_diputadoRoldosLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPnl_diputadoRoldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_diputadoRoldosLayout.createSequentialGroup()
                        .addComponent(jRdBtn_nombreDiputado4)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_diputadoRoldosLayout.createSequentialGroup()
                        .addComponent(jLbl_imagenDiputado4)
                        .addGap(27, 27, 27))))
        );
        jPnl_diputadoRoldosLayout.setVerticalGroup(
            jPnl_diputadoRoldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_diputadoRoldosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbl_imagenDiputado4)
                .addGap(18, 18, 18)
                .addComponent(jRdBtn_nombreDiputado4)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnl_diputadosLayout = new javax.swing.GroupLayout(jPnl_diputados);
        jPnl_diputados.setLayout(jPnl_diputadosLayout);
        jPnl_diputadosLayout.setHorizontalGroup(
            jPnl_diputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_diputadosLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPnl_diputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnl_diputadosLayout.createSequentialGroup()
                        .addComponent(jPnl_diputadoMahuad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPnl_diputadoRoldos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnl_diputadosLayout.createSequentialGroup()
                        .addComponent(jPnl_diputadoCorrea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPnl_diputadoGutierrez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );

        jPnl_diputadosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPnl_diputadoCorrea, jPnl_diputadoGutierrez, jPnl_diputadoMahuad, jPnl_diputadoRoldos});

        jPnl_diputadosLayout.setVerticalGroup(
            jPnl_diputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_diputadosLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPnl_diputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPnl_diputadoCorrea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPnl_diputadoGutierrez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnl_diputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnl_diputadoMahuad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPnl_diputadoRoldos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPnl_diputadosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPnl_diputadoCorrea, jPnl_diputadoGutierrez, jPnl_diputadoMahuad, jPnl_diputadoRoldos});

        jPnl_alcaldes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ALCALDES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 102))); // NOI18N
        jPnl_alcaldes.setName("jPnl_alcaldes"); // NOI18N

        jPnl_alcaldeCorrea.setBackground(new java.awt.Color(255, 255, 255));
        jPnl_alcaldeCorrea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eco. Rafael Correa", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(51, 0, 102))); // NOI18N
        jPnl_alcaldeCorrea.setName("jPnl_alcaldeCorrea"); // NOI18N

        jLbl_imagenAlcalde1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/candidato5.JPG"))); // NOI18N
        jLbl_imagenAlcalde1.setName("jLbl_imagenAlcalde1"); // NOI18N

        jRdBtn_nombreAlcalde1.setFont(new java.awt.Font("Tahoma", 1, 10));
        jRdBtn_nombreAlcalde1.setForeground(new java.awt.Color(51, 0, 102));
        jRdBtn_nombreAlcalde1.setText("Eco. Renato Benavides");
        jRdBtn_nombreAlcalde1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 102)));
        jRdBtn_nombreAlcalde1.setName("jRdBtn_nombreAlcalde1"); // NOI18N

        javax.swing.GroupLayout jPnl_alcaldeCorreaLayout = new javax.swing.GroupLayout(jPnl_alcaldeCorrea);
        jPnl_alcaldeCorrea.setLayout(jPnl_alcaldeCorreaLayout);
        jPnl_alcaldeCorreaLayout.setHorizontalGroup(
            jPnl_alcaldeCorreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_alcaldeCorreaLayout.createSequentialGroup()
                .addGroup(jPnl_alcaldeCorreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnl_alcaldeCorreaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLbl_imagenAlcalde1))
                    .addGroup(jPnl_alcaldeCorreaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRdBtn_nombreAlcalde1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPnl_alcaldeCorreaLayout.setVerticalGroup(
            jPnl_alcaldeCorreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_alcaldeCorreaLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLbl_imagenAlcalde1)
                .addGap(18, 18, 18)
                .addComponent(jRdBtn_nombreAlcalde1)
                .addContainerGap())
        );

        jPnl_alcaldeGutierrez.setBackground(new java.awt.Color(255, 255, 255));
        jPnl_alcaldeGutierrez.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crnl. Lucio Gutierrez", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(51, 0, 102))); // NOI18N
        jPnl_alcaldeGutierrez.setName("jPnl_alcaldeGutierrez"); // NOI18N

        jLbl_imagenAlcalde2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/candidato6.JPG"))); // NOI18N
        jLbl_imagenAlcalde2.setName("jLbl_imagenAlcalde2"); // NOI18N

        jRdBtn_nombreAlcalde2.setFont(new java.awt.Font("Tahoma", 1, 10));
        jRdBtn_nombreAlcalde2.setForeground(new java.awt.Color(51, 0, 102));
        jRdBtn_nombreAlcalde2.setText("Lcd. Luis Morán");
        jRdBtn_nombreAlcalde2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 102)));
        jRdBtn_nombreAlcalde2.setName("jRdBtn_nombreAlcalde2"); // NOI18N

        javax.swing.GroupLayout jPnl_alcaldeGutierrezLayout = new javax.swing.GroupLayout(jPnl_alcaldeGutierrez);
        jPnl_alcaldeGutierrez.setLayout(jPnl_alcaldeGutierrezLayout);
        jPnl_alcaldeGutierrezLayout.setHorizontalGroup(
            jPnl_alcaldeGutierrezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_alcaldeGutierrezLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jRdBtn_nombreAlcalde2)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_alcaldeGutierrezLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLbl_imagenAlcalde2)
                .addGap(43, 43, 43))
        );
        jPnl_alcaldeGutierrezLayout.setVerticalGroup(
            jPnl_alcaldeGutierrezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_alcaldeGutierrezLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLbl_imagenAlcalde2)
                .addGap(18, 18, 18)
                .addComponent(jRdBtn_nombreAlcalde2)
                .addContainerGap())
        );

        jPnl_alcaldeMahuad.setBackground(new java.awt.Color(255, 255, 255));
        jPnl_alcaldeMahuad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dr. Jamil Mahuad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(51, 0, 102))); // NOI18N
        jPnl_alcaldeMahuad.setName("jPnl_alcaldeMahuad"); // NOI18N

        jLbl_imagenAlcalde3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/candidato7.JPG"))); // NOI18N
        jLbl_imagenAlcalde3.setName("jLbl_imagenAlcalde3"); // NOI18N

        jRdBtn_nombreAlcalde3.setFont(new java.awt.Font("Tahoma", 1, 10));
        jRdBtn_nombreAlcalde3.setForeground(new java.awt.Color(51, 0, 102));
        jRdBtn_nombreAlcalde3.setText("Ab. Fernando Lopéz");
        jRdBtn_nombreAlcalde3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 102)));
        jRdBtn_nombreAlcalde3.setName("jRdBtn_nombreAlcalde3"); // NOI18N
        jRdBtn_nombreAlcalde3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdBtn_nombreAlcalde3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnl_alcaldeMahuadLayout = new javax.swing.GroupLayout(jPnl_alcaldeMahuad);
        jPnl_alcaldeMahuad.setLayout(jPnl_alcaldeMahuadLayout);
        jPnl_alcaldeMahuadLayout.setHorizontalGroup(
            jPnl_alcaldeMahuadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_alcaldeMahuadLayout.createSequentialGroup()
                .addGroup(jPnl_alcaldeMahuadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnl_alcaldeMahuadLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jRdBtn_nombreAlcalde3))
                    .addGroup(jPnl_alcaldeMahuadLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLbl_imagenAlcalde3)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPnl_alcaldeMahuadLayout.setVerticalGroup(
            jPnl_alcaldeMahuadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_alcaldeMahuadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbl_imagenAlcalde3)
                .addGap(18, 18, 18)
                .addComponent(jRdBtn_nombreAlcalde3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPnl_alcaldeRoldos.setBackground(new java.awt.Color(255, 255, 255));
        jPnl_alcaldeRoldos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ab. Jaime Roldos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(51, 0, 102))); // NOI18N
        jPnl_alcaldeRoldos.setName("jPnl_alcaldeRoldos"); // NOI18N

        jLbl_imagenAlcalde4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/candidato8.JPG"))); // NOI18N
        jLbl_imagenAlcalde4.setName("jLbl_imagenAlcalde4"); // NOI18N

        jRdBtn_nombreAlcalde4.setFont(new java.awt.Font("Tahoma", 1, 10));
        jRdBtn_nombreAlcalde4.setForeground(new java.awt.Color(51, 0, 102));
        jRdBtn_nombreAlcalde4.setText("Ing. Armando Peñaherrera");
        jRdBtn_nombreAlcalde4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 102)));
        jRdBtn_nombreAlcalde4.setName("jRdBtn_nombreAlcalde4"); // NOI18N

        javax.swing.GroupLayout jPnl_alcaldeRoldosLayout = new javax.swing.GroupLayout(jPnl_alcaldeRoldos);
        jPnl_alcaldeRoldos.setLayout(jPnl_alcaldeRoldosLayout);
        jPnl_alcaldeRoldosLayout.setHorizontalGroup(
            jPnl_alcaldeRoldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRdBtn_nombreAlcalde4)
            .addGroup(jPnl_alcaldeRoldosLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLbl_imagenAlcalde4))
        );
        jPnl_alcaldeRoldosLayout.setVerticalGroup(
            jPnl_alcaldeRoldosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_alcaldeRoldosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbl_imagenAlcalde4)
                .addGap(18, 18, 18)
                .addComponent(jRdBtn_nombreAlcalde4)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnl_alcaldesLayout = new javax.swing.GroupLayout(jPnl_alcaldes);
        jPnl_alcaldes.setLayout(jPnl_alcaldesLayout);
        jPnl_alcaldesLayout.setHorizontalGroup(
            jPnl_alcaldesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_alcaldesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnl_alcaldesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnl_alcaldesLayout.createSequentialGroup()
                        .addComponent(jPnl_alcaldeCorrea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPnl_alcaldeGutierrez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnl_alcaldesLayout.createSequentialGroup()
                        .addComponent(jPnl_alcaldeMahuad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPnl_alcaldeRoldos, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPnl_alcaldesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPnl_alcaldeCorrea, jPnl_alcaldeGutierrez, jPnl_alcaldeMahuad, jPnl_alcaldeRoldos});

        jPnl_alcaldesLayout.setVerticalGroup(
            jPnl_alcaldesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_alcaldesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnl_alcaldesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnl_alcaldeGutierrez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnl_alcaldeCorrea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnl_alcaldesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnl_alcaldeRoldos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnl_alcaldeMahuad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        jPnl_alcaldesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPnl_alcaldeCorrea, jPnl_alcaldeGutierrez, jPnl_alcaldeMahuad, jPnl_alcaldeRoldos});

        jBtn_ir_votantes.setFont(new java.awt.Font("Tahoma", 1, 12));
        jBtn_ir_votantes.setForeground(new java.awt.Color(0, 0, 153));
        jBtn_ir_votantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/hg.JPG"))); // NOI18N
        jBtn_ir_votantes.setText("ACEPTAR");
        jBtn_ir_votantes.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 102)));
        jBtn_ir_votantes.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jBtn_ir_votantes.setName("jBtn_ir_votantes"); // NOI18N
        jBtn_ir_votantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_ir_votantesMouseClicked(evt);
            }
        });

        jLbl_reloj.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLbl_reloj.setForeground(new java.awt.Color(0, 0, 102));
        jLbl_reloj.setName("jLbl_reloj"); // NOI18N

        jPnl_datosPersonales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS PERSONALES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(51, 0, 102))); // NOI18N
        jPnl_datosPersonales.setName("jPnl_datosPersonales"); // NOI18N

        jLbl_apellido.setFont(new java.awt.Font("Aharoni", 1, 12));
        jLbl_apellido.setForeground(new java.awt.Color(102, 0, 102));
        jLbl_apellido.setText("APELLIDO:");
        jLbl_apellido.setName("jLbl_apellido"); // NOI18N

        jLbl_nombre.setFont(new java.awt.Font("Aharoni", 1, 12));
        jLbl_nombre.setForeground(new java.awt.Color(102, 0, 102));
        jLbl_nombre.setText("NOMBRE:");
        jLbl_nombre.setName("jLbl_nombre"); // NOI18N

        jLbl_apellidoPersonal.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLbl_apellidoPersonal.setForeground(new java.awt.Color(153, 0, 0));
        jLbl_apellidoPersonal.setName("jLbl_apellidoPersonal"); // NOI18N

        jLbl_nombrePersonal.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLbl_nombrePersonal.setForeground(new java.awt.Color(153, 0, 0));
        jLbl_nombrePersonal.setName("jLbl_nombrePersonal"); // NOI18N

        jLbl_CI.setFont(new java.awt.Font("Aharoni", 1, 12));
        jLbl_CI.setForeground(new java.awt.Color(102, 0, 102));
        jLbl_CI.setText("C.I.:");
        jLbl_CI.setName("jLbl_CI"); // NOI18N

        jLbl_CIPersonal.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLbl_CIPersonal.setForeground(new java.awt.Color(153, 0, 0));
        jLbl_CIPersonal.setName("jLbl_CIPersonal"); // NOI18N

        jLbl_codigo.setFont(new java.awt.Font("Aharoni", 1, 12));
        jLbl_codigo.setForeground(new java.awt.Color(102, 0, 102));
        jLbl_codigo.setText("CODIGO:");
        jLbl_codigo.setName("jLbl_codigo"); // NOI18N

        jLbl_codigoPersonal.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLbl_codigoPersonal.setForeground(new java.awt.Color(153, 0, 0));
        jLbl_codigoPersonal.setName("jLbl_codigoPersonal"); // NOI18N

        javax.swing.GroupLayout jPnl_datosPersonalesLayout = new javax.swing.GroupLayout(jPnl_datosPersonales);
        jPnl_datosPersonales.setLayout(jPnl_datosPersonalesLayout);
        jPnl_datosPersonalesLayout.setHorizontalGroup(
            jPnl_datosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_datosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnl_datosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnl_datosPersonalesLayout.createSequentialGroup()
                        .addComponent(jLbl_codigo)
                        .addGap(17, 17, 17)
                        .addComponent(jLbl_codigoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnl_datosPersonalesLayout.createSequentialGroup()
                        .addComponent(jLbl_CI)
                        .addGap(48, 48, 48)
                        .addComponent(jLbl_CIPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_datosPersonalesLayout.createSequentialGroup()
                        .addComponent(jLbl_nombre)
                        .addGap(13, 13, 13)
                        .addComponent(jLbl_nombrePersonal, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_datosPersonalesLayout.createSequentialGroup()
                        .addComponent(jLbl_apellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jLbl_apellidoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPnl_datosPersonalesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLbl_CIPersonal, jLbl_apellidoPersonal, jLbl_codigoPersonal, jLbl_nombrePersonal});

        jPnl_datosPersonalesLayout.setVerticalGroup(
            jPnl_datosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_datosPersonalesLayout.createSequentialGroup()
                .addGroup(jPnl_datosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLbl_codigoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbl_codigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnl_datosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLbl_CIPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbl_CI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnl_datosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLbl_nombrePersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbl_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnl_datosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLbl_apellidoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbl_apellido))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnl_datosPersonalesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLbl_CIPersonal, jLbl_apellidoPersonal, jLbl_codigoPersonal, jLbl_nombrePersonal});

        jLbl_gifmuñeco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/muñeco.gif"))); // NOI18N
        jLbl_gifmuñeco.setName("jLbl_gifmuñeco"); // NOI18N

        jLbl_gifmapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/ecuador_mwp.gif"))); // NOI18N
        jLbl_gifmapa.setName("jLbl_gifmapa"); // NOI18N

        jLbl_imagenmuñeco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/kjj.jpeg"))); // NOI18N
        jLbl_imagenmuñeco.setName("jLbl_imagenmuñeco"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLbl_titulo_listaDiputadosAlcaldes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLbl_gifmuñeco)
                        .addGap(113, 113, 113)
                        .addComponent(jPnl_datosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLbl_gifmapa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLbl_imagenmuñeco))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPnl_diputados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPnl_alcaldes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLbl_reloj, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(203, 203, 203)
                                .addComponent(jBtn_ir_votantes)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPnl_alcaldes, jPnl_diputados});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbl_titulo_listaDiputadosAlcaldes)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPnl_datosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbl_gifmuñeco)
                                .addGap(41, 41, 41))
                            .addComponent(jLbl_imagenmuñeco)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLbl_gifmapa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnl_alcaldes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnl_diputados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbl_reloj, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_ir_votantes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPnl_alcaldes, jPnl_diputados});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_ir_votantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_ir_votantesMouseClicked
        try {
            // TODO add your handling code here:
            if (jRdBtn_nombreDiputado1.isSelected() == true && jRdBtn_nombreDiputado2.isSelected() == false && jRdBtn_nombreDiputado3.isSelected() == false && jRdBtn_nombreDiputado4.isSelected() == false) {
                //condicion para suma votos c1
                FileWriter fwmostarnombres = null; //inicializacion de variable para escribir en fichero
                try {
                    File mostarnombres = new File("votos_diputados.txt"); //cierra fichero
                    fwmostarnombres = new FileWriter(mostarnombres, true);
                    PrintWriter pmostarnombres = new PrintWriter(fwmostarnombres);
                    pmostarnombres.println("Cdp_Gdp_Mdp_Rdp_B_N      1       0      0      0      0      0"); //guarda en fichero
                    pmostarnombres.close(); //cierra fichero
                } catch (IOException ex) {
                    Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        fwmostarnombres.close(); //cierra fichero
                    } catch (IOException ex) {
                        Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            if (jRdBtn_nombreDiputado1.isSelected() == false && jRdBtn_nombreDiputado2.isSelected() == true && jRdBtn_nombreDiputado3.isSelected() == false && jRdBtn_nombreDiputado4.isSelected() == false) {
                //condicion para suma votos c2
                FileWriter fwmostarnombres = null;
                try {
                    File mostarnombres = new File("votos_diputados.txt"); //abre fichero
                    fwmostarnombres = new FileWriter(mostarnombres, true);
                    PrintWriter pmostarnombres = new PrintWriter(fwmostarnombres);
                    pmostarnombres.println("Cdp_Gdp_Mdp_Rdp_B_N       0       1       0       0       0       0"); //guarda voto en el fichero
                    pmostarnombres.close();
                } catch (IOException ex) {
                    Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        fwmostarnombres.close();
                    } catch (IOException ex) {
                        Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            if (jRdBtn_nombreDiputado1.isSelected() == false && jRdBtn_nombreDiputado2.isSelected() == false && jRdBtn_nombreDiputado3.isSelected() == true && jRdBtn_nombreDiputado4.isSelected() == false) {
                //condicion para suma votos c3
                FileWriter fwmostarnombres = null;
                try {
                    File mostarnombres = new File("votos_diputados.txt");
                    fwmostarnombres = new FileWriter(mostarnombres, true);
                    PrintWriter pmostarnombres = new PrintWriter(fwmostarnombres);
                    pmostarnombres.println("Cdp_Gdp_Mdp_Rdp_B_N       0       0       1       0       0       0");
                    pmostarnombres.close();
                } catch (IOException ex) {
                    Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        fwmostarnombres.close();
                    } catch (IOException ex) {
                        Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            if (jRdBtn_nombreDiputado1.isSelected() == false && jRdBtn_nombreDiputado2.isSelected() == false && jRdBtn_nombreDiputado3.isSelected() == false && jRdBtn_nombreDiputado4.isSelected() == true) {
                //condicion para suma votos c4
                FileWriter fwmostarnombres = null;
                try {
                    File mostarnombres = new File("votos_diputados.txt");
                    fwmostarnombres = new FileWriter(mostarnombres, true);
                    PrintWriter pmostarnombres = new PrintWriter(fwmostarnombres);
                    pmostarnombres.println("Cdp_Gdp_Mdp_Rdp_B_N       0       0       0       1       0       0");
                    pmostarnombres.close();
                } catch (IOException ex) {
                    Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        fwmostarnombres.close();
                    } catch (IOException ex) {
                        Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            if (jRdBtn_nombreDiputado1.isSelected() == false && jRdBtn_nombreDiputado2.isSelected() == false && jRdBtn_nombreDiputado3.isSelected() == false && jRdBtn_nombreDiputado4.isSelected() == false) {
                //condicion para suma votos en blanco
                FileWriter fwmostarnombres = null;
                try {
                    File mostarnombres = new File("votos_diputados.txt");
                    fwmostarnombres = new FileWriter(mostarnombres, true);
                    PrintWriter pmostarnombres = new PrintWriter(fwmostarnombres);
                    pmostarnombres.println("Cdp_Gdp_Mdp_Rdp_B_N       0       0       0       0       1       0");
                    pmostarnombres.close();
                } catch (IOException ex) {
                    Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        fwmostarnombres.close();
                    } catch (IOException ex) {
                        Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            if ((jRdBtn_nombreDiputado1.isSelected() == false && jRdBtn_nombreDiputado2.isSelected() == false && jRdBtn_nombreDiputado3.isSelected() == true && jRdBtn_nombreDiputado4.isSelected() == true) || jRdBtn_nombreDiputado1.isSelected() == false && jRdBtn_nombreDiputado2.isSelected() == true && jRdBtn_nombreDiputado3.isSelected() == false && jRdBtn_nombreDiputado4.isSelected() == true || jRdBtn_nombreDiputado1.isSelected() == false && jRdBtn_nombreDiputado2.isSelected() == true && jRdBtn_nombreDiputado3.isSelected() == true && jRdBtn_nombreDiputado4.isSelected() == false || jRdBtn_nombreDiputado1.isSelected() == false && jRdBtn_nombreDiputado2.isSelected() == true && jRdBtn_nombreDiputado3.isSelected() == true && jRdBtn_nombreDiputado4.isSelected() == true || jRdBtn_nombreDiputado1.isSelected() == true && jRdBtn_nombreDiputado2.isSelected() == false && jRdBtn_nombreDiputado3.isSelected() == false && jRdBtn_nombreDiputado4.isSelected() == true || jRdBtn_nombreDiputado1.isSelected() == true && jRdBtn_nombreDiputado2.isSelected() == false && jRdBtn_nombreDiputado3.isSelected() == true && jRdBtn_nombreDiputado4.isSelected() == false || jRdBtn_nombreDiputado1.isSelected() == true && jRdBtn_nombreDiputado2.isSelected() == false && jRdBtn_nombreDiputado3.isSelected() == true && jRdBtn_nombreDiputado4.isSelected() == true || jRdBtn_nombreDiputado1.isSelected() == true && jRdBtn_nombreDiputado2.isSelected() == true && jRdBtn_nombreDiputado3.isSelected() == false && jRdBtn_nombreDiputado4.isSelected() == false || jRdBtn_nombreDiputado1.isSelected() == true && jRdBtn_nombreDiputado2.isSelected() == true && jRdBtn_nombreDiputado3.isSelected() == false && jRdBtn_nombreDiputado4.isSelected() == true || jRdBtn_nombreDiputado1.isSelected() == true && jRdBtn_nombreDiputado2.isSelected() == true && jRdBtn_nombreDiputado3.isSelected() == true && jRdBtn_nombreDiputado4.isSelected() == false || jRdBtn_nombreDiputado1.isSelected() == true && jRdBtn_nombreDiputado2.isSelected() == true && jRdBtn_nombreDiputado3.isSelected() == true && jRdBtn_nombreDiputado4.isSelected() == true) {
                //condicion para suma votos correa
                FileWriter fwmostarnombres = null;
                try {
                    File mostarnombres = new File("votos_diputados.txt");
                    fwmostarnombres = new FileWriter(mostarnombres, true);
                    PrintWriter pmostarnombres = new PrintWriter(fwmostarnombres);
                    pmostarnombres.println("Cdp_Gdp_Mdp_Rdp_B_N       0       0       0       0       0       1");
                    pmostarnombres.close();
                } catch (IOException ex) {
                    Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        fwmostarnombres.close();
                    } catch (IOException ex) {
                        Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            if (jRdBtn_nombreAlcalde1.isSelected() == true && jRdBtn_nombreAlcalde2.isSelected() == false && jRdBtn_nombreAlcalde3.isSelected() == false && jRdBtn_nombreAlcalde4.isSelected() == false) {
                //condicion para suma votos c1
                FileWriter fwmostarnombres = null; //inicializacion de variable para escribir en fichero
                try {
                    File mostarnombres = new File("votos_alcaldes.txt"); //cierra fichero
                    fwmostarnombres = new FileWriter(mostarnombres, true);
                    PrintWriter pmostarnombres = new PrintWriter(fwmostarnombres);
                    pmostarnombres.println("Cdp_Gdp_Mdp_Rdp_B_N      1       0      0      0      0      0"); //guarda en fichero
                    pmostarnombres.close(); //cierra fichero
                } catch (IOException ex) {
                    Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        fwmostarnombres.close(); //cierra fichero
                    } catch (IOException ex) {
                        Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            if (jRdBtn_nombreAlcalde1.isSelected() == false && jRdBtn_nombreAlcalde2.isSelected() == true && jRdBtn_nombreAlcalde3.isSelected() == false && jRdBtn_nombreAlcalde4.isSelected() == false) {
                //condicion para suma votos c2
                FileWriter fwmostarnombres = null;
                try {
                    File mostarnombres = new File("votos_alcaldes.txt"); //abre fichero
                    fwmostarnombres = new FileWriter(mostarnombres, true);
                    PrintWriter pmostarnombres = new PrintWriter(fwmostarnombres);
                    pmostarnombres.println("Cdp_Gdp_Mdp_Rdp_B_N       0       1       0       0       0       0"); //guarda voto en el fichero
                    pmostarnombres.close();
                } catch (IOException ex) {
                    Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        fwmostarnombres.close();
                    } catch (IOException ex) {
                        Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            if (jRdBtn_nombreAlcalde1.isSelected() == false && jRdBtn_nombreAlcalde2.isSelected() == false && jRdBtn_nombreAlcalde3.isSelected() == true && jRdBtn_nombreAlcalde4.isSelected() == false) {
                //condicion para suma votos c3
                FileWriter fwmostarnombres = null;
                try {
                    File mostarnombres = new File("votos_alcaldes.txt");
                    fwmostarnombres = new FileWriter(mostarnombres, true);
                    PrintWriter pmostarnombres = new PrintWriter(fwmostarnombres);
                    pmostarnombres.println("Cdp_Gdp_Mdp_Rdp_B_N       0       0       1       0       0       0");
                    pmostarnombres.close();
                } catch (IOException ex) {
                    Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        fwmostarnombres.close();
                    } catch (IOException ex) {
                        Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            if (jRdBtn_nombreAlcalde1.isSelected() == false && jRdBtn_nombreAlcalde2.isSelected() == false && jRdBtn_nombreAlcalde3.isSelected() == false && jRdBtn_nombreAlcalde4.isSelected() == true) {
                //condicion para suma votos c4
                FileWriter fwmostarnombres = null;
                try {
                    File mostarnombres = new File("votos_alcaldes.txt");
                    fwmostarnombres = new FileWriter(mostarnombres, true);
                    PrintWriter pmostarnombres = new PrintWriter(fwmostarnombres);
                    pmostarnombres.println("Cdp_Gdp_Mdp_Rdp_B_N       0       0       0       1       0       0");
                    pmostarnombres.close();
                } catch (IOException ex) {
                    Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        fwmostarnombres.close();
                    } catch (IOException ex) {
                        Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            if (jRdBtn_nombreAlcalde1.isSelected() == false && jRdBtn_nombreAlcalde2.isSelected() == false && jRdBtn_nombreAlcalde3.isSelected() == false && jRdBtn_nombreAlcalde4.isSelected() == false) {
                //condicion para suma votos en blanco
                FileWriter fwmostarnombres = null;
                try {
                    File mostarnombres = new File("votos_alcaldes.txt");
                    fwmostarnombres = new FileWriter(mostarnombres, true);
                    PrintWriter pmostarnombres = new PrintWriter(fwmostarnombres);
                    pmostarnombres.println("Cdp_Gdp_Mdp_Rdp_B_N       0       0       0       0       1       0");
                    pmostarnombres.close();
                } catch (IOException ex) {
                    Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        fwmostarnombres.close();
                    } catch (IOException ex) {
                        Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            if ((jRdBtn_nombreAlcalde1.isSelected() == false && jRdBtn_nombreAlcalde2.isSelected() == false && jRdBtn_nombreAlcalde3.isSelected() == true && jRdBtn_nombreAlcalde4.isSelected() == true) || jRdBtn_nombreAlcalde1.isSelected() == false && jRdBtn_nombreAlcalde2.isSelected() == true && jRdBtn_nombreAlcalde3.isSelected() == false && jRdBtn_nombreAlcalde4.isSelected() == true || jRdBtn_nombreAlcalde1.isSelected() == false && jRdBtn_nombreAlcalde2.isSelected() == true && jRdBtn_nombreAlcalde3.isSelected() == true && jRdBtn_nombreAlcalde4.isSelected() == false || jRdBtn_nombreAlcalde1.isSelected() == false && jRdBtn_nombreAlcalde2.isSelected() == true && jRdBtn_nombreAlcalde3.isSelected() == true && jRdBtn_nombreAlcalde4.isSelected() == true || jRdBtn_nombreAlcalde1.isSelected() == true && jRdBtn_nombreAlcalde2.isSelected() == false && jRdBtn_nombreAlcalde3.isSelected() == false && jRdBtn_nombreAlcalde4.isSelected() == true || jRdBtn_nombreAlcalde1.isSelected() == true && jRdBtn_nombreAlcalde2.isSelected() == false && jRdBtn_nombreAlcalde3.isSelected() == true && jRdBtn_nombreAlcalde4.isSelected() == false || jRdBtn_nombreAlcalde1.isSelected() == true && jRdBtn_nombreAlcalde2.isSelected() == false && jRdBtn_nombreAlcalde3.isSelected() == true && jRdBtn_nombreAlcalde4.isSelected() == true || jRdBtn_nombreAlcalde1.isSelected() == true && jRdBtn_nombreAlcalde2.isSelected() == true && jRdBtn_nombreAlcalde3.isSelected() == false && jRdBtn_nombreAlcalde4.isSelected() == false || jRdBtn_nombreAlcalde1.isSelected() == true && jRdBtn_nombreAlcalde2.isSelected() == true && jRdBtn_nombreAlcalde3.isSelected() == false && jRdBtn_nombreAlcalde4.isSelected() == true || jRdBtn_nombreAlcalde1.isSelected() == true && jRdBtn_nombreAlcalde2.isSelected() == true && jRdBtn_nombreAlcalde3.isSelected() == true && jRdBtn_nombreAlcalde4.isSelected() == false || jRdBtn_nombreAlcalde1.isSelected() == true && jRdBtn_nombreAlcalde2.isSelected() == true && jRdBtn_nombreAlcalde3.isSelected() == true && jRdBtn_nombreAlcalde4.isSelected() == true) {
                //condicion para suma votos correa
                FileWriter fwmostarnombres = null;
                try {
                    File mostarnombres = new File("votos_alcaldes.txt");
                    fwmostarnombres = new FileWriter(mostarnombres, true);
                    PrintWriter pmostarnombres = new PrintWriter(fwmostarnombres);
                    pmostarnombres.println("Cdp_Gdp_Mdp_Rdp_B_N       0       0       0       0       0       1");
                    pmostarnombres.close();
                } catch (IOException ex) {
                    Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        fwmostarnombres.close();
                    } catch (IOException ex) {
                        Logger.getLogger(papeleta_presidente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            JOptionPane.showMessageDialog(null, "GRACIAS POR SU PARTICIPACION\n ***SU VOTO SE HA GUARDADO***");
            // codigo para mostrar los datos de la persona que esta votando
            File archivo1 = null;
            FileReader fr1 = null;
            BufferedReader br1 = null;
            archivo1 = new File("Compararcedula.txt"); //abre fichero para verificar que la persona este empadronada y pueda votar solo una vez
            fr1 = new FileReader(archivo1);
            br1 = new BufferedReader(fr1);
            String linea = ""; //inicializa linea para poder leer linea de fichero
            while ((linea = br1.readLine()) != null) //hace la comparacion hasta que exista linea en blanco
            {
                jLbl_CIPersonal.setText("" + linea); //muestra la CI de la persona que esta votando
            }
            String cedula1 = (String) jLbl_CIPersonal.getText(); //guarda la cedula de identidad de la persona que vota
            buscar busempa = new buscar("empa.txt"); //llamada a clase buscar
            String datos = busempa.BuscarDatos(cedula1); //llamada a metodo BuscarDatos de clase buscar //verifica que exista la cedula ingresada este fichero
            if (datos.equals("")) {
                //mensaje de no existe
                JOptionPane.showMessageDialog(null, "NO ESTA EMPADRONADO", "  ERROR", 0); //mensaje de no existe
            } else {
                StringTokenizer tok = new StringTokenizer(datos, "\t"); //codigo para poder leer cada dato de empadronado
                String cedula = tok.nextToken(); //salta al siguiente dato de empadronado
                String codigo = tok.nextToken().toString(); //guarda codigo de empadronado
                String nombre = tok.nextToken().toString(); //guarda nombre de fichero
                String apellido = tok.nextToken().toString(); //guarda apellido de fichero
                tok.nextToken().toString();
                String provincia = tok.nextToken().toString(); //guarda apellido de fichero
                ImprimeCertificadoVotos ir = new ImprimeCertificadoVotos(); // crea objeto para ir a nueva ventana
                this.setVisible(false); //oculta la ventana actual
                //            ir.setVisible(true); // para que la ventana este siempre centrada
                //            ir.setLocationRelativeTo(null); // para que la ventana este siempre centrada
                imprimir.ingresarTexto("\n   ANVERSO\n" + "________________________________________________________________________________\n\n"
                                        + "                                                                REPUBLICA DEL ECUADOR\n"
                                        + "                                                        SISTEMA ELECTRONICO DE VOTACIONES\n"
                                        + "                                                              CERTIFICADO DE VOTACION\n"
                                        + "                                                            ELECCIONES GENERALES  " + 2011 + " \n"
                                        + "                                             \n"
                                        + "                                          Codigo:    " + codigo + "                                    CI: " + cedula + "\n"
                                        + "                                          Nombre:    " + nombre + "  " + apellido + "\n"
                                        + "                                          Provincia: " + provincia + "\n"
                                        + "________________________________________________________________________________"
                                        + "\n\n\n   REVERSO\n"
                                        + "________________________________________________________________________________\n\n"
                                        + "                                                                              CIUDADANO(A)\n\n"
                                        + "                                                                          Este documento acredita\n"
                                        + "                                                                          que usted sufragó en las\n"
                                        + "                                                                            Elecciones Generales\n"
                                        + "                                                                                         2011\n\n"
                                        + "                                                         ESTE CERTIFICADO SIRVE PARA TODOS\n"
                                        + "                                                          LOS TRAMITES PUBLICOS Y PRIVADOS\n"
                                        + "________________________________________________________________________________");
                imprimir.setVisible(true);
            }
            //
            //
        } catch (IOException ex) {
            Logger.getLogger(papeleta_diputados_alcaldes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtn_ir_votantesMouseClicked

    private void jRdBtn_nombreDiputado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdBtn_nombreDiputado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRdBtn_nombreDiputado1ActionPerformed

    private void jRdBtn_nombreAlcalde3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdBtn_nombreAlcalde3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRdBtn_nombreAlcalde3ActionPerformed

    /**
    * @param args the command line arguments
  */
// public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new papeleta_diputados_alcaldes().setVisible(true); // clase principal
//                } catch (FileNotFoundException ex) {
//                    Logger.getLogger(ImprimeCertificadoVotos.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (IOException ex) {
//                    Logger.getLogger(ImprimeCertificadoVotos.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_ir_votantes;
    private javax.swing.JLabel jLbl_CI;
    private javax.swing.JLabel jLbl_CIPersonal;
    private javax.swing.JLabel jLbl_apellido;
    private javax.swing.JLabel jLbl_apellidoPersonal;
    private javax.swing.JLabel jLbl_codigo;
    private javax.swing.JLabel jLbl_codigoPersonal;
    private javax.swing.JLabel jLbl_gifmapa;
    private javax.swing.JLabel jLbl_gifmuñeco;
    private javax.swing.JLabel jLbl_imagenAlcalde1;
    private javax.swing.JLabel jLbl_imagenAlcalde2;
    private javax.swing.JLabel jLbl_imagenAlcalde3;
    private javax.swing.JLabel jLbl_imagenAlcalde4;
    private javax.swing.JLabel jLbl_imagenDiputado1;
    private javax.swing.JLabel jLbl_imagenDiputado2;
    private javax.swing.JLabel jLbl_imagenDiputado3;
    private javax.swing.JLabel jLbl_imagenDiputado4;
    private javax.swing.JLabel jLbl_imagenmuñeco;
    private javax.swing.JLabel jLbl_nombre;
    private javax.swing.JLabel jLbl_nombrePersonal;
    private javax.swing.JLabel jLbl_reloj;
    private javax.swing.JLabel jLbl_titulo_listaDiputadosAlcaldes;
    private javax.swing.JPanel jPnl_alcaldeCorrea;
    private javax.swing.JPanel jPnl_alcaldeGutierrez;
    private javax.swing.JPanel jPnl_alcaldeMahuad;
    private javax.swing.JPanel jPnl_alcaldeRoldos;
    private javax.swing.JPanel jPnl_alcaldes;
    private javax.swing.JPanel jPnl_datosPersonales;
    private javax.swing.JPanel jPnl_diputadoCorrea;
    private javax.swing.JPanel jPnl_diputadoGutierrez;
    private javax.swing.JPanel jPnl_diputadoMahuad;
    private javax.swing.JPanel jPnl_diputadoRoldos;
    private javax.swing.JPanel jPnl_diputados;
    private javax.swing.JRadioButton jRdBtn_nombreAlcalde1;
    private javax.swing.JRadioButton jRdBtn_nombreAlcalde2;
    private javax.swing.JRadioButton jRdBtn_nombreAlcalde3;
    private javax.swing.JRadioButton jRdBtn_nombreAlcalde4;
    private javax.swing.JRadioButton jRdBtn_nombreDiputado1;
    private javax.swing.JRadioButton jRdBtn_nombreDiputado2;
    private javax.swing.JRadioButton jRdBtn_nombreDiputado3;
    private javax.swing.JRadioButton jRdBtn_nombreDiputado4;
    // End of variables declaration//GEN-END:variables

}
