package proyecto_sev1;
import clases.*;
import java.io.*;
import javax.swing.*;
import java.io.*;
import java.util.*;
import javax.swing.JOptionPane;
import java.awt.event.*;
import java.util.logging.Level;
import java.util.logging.Logger;
public class registro extends JFrameConFondo {
    /** Creates new form registro */
    public registro() {
        initComponents();


        setImagen("Recursos/registroB.jpg");
        Reloj modelo = new Reloj();
        modelo.addObserver(new Observer() {

            public void update(Observable unObservable, Object dato) {
                jLbl_reloj.setText("" + dato);
            }
        });
    }
    private boolean existeRegistro() {
        boolean existe = false;
        buscar busca = new buscar("cedulas.txt");
        String dato = busca.BuscarDatos(jTxFld_numCedula.getText().toString());
        if (dato.equals("")) {
            existe = false;
        } else {
            existe = true;
        }
        return existe;
    }
    private boolean listo() {
        boolean ok = false;

        if (jTxFld_numCedula.getText().toString().equals("")) {
            ok = false;
        } else {
            ok = true;
        }
        return ok;
    }
    private boolean existeRegistro1() {
        boolean existe = false;
        buscar busca = new buscar("Compararcedula.txt");
        String dato = busca.BuscarDatos(jTxFld_numCedula.getText().toString());
        if (dato.equals("")) {
            existe = false;
        } else {
            existe = true;
        }
        return existe;
    }
    private boolean listo1() {
        boolean ok = false;
        if (jTxFld_numCedula.getText().toString().equals("")) {
            ok = false;
        } else {
            ok = true;
        }
        return ok;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbl_tituloRegistro = new javax.swing.JLabel();
        jLbl_CI = new javax.swing.JLabel();
        jTxFld_numCedula = new javax.swing.JTextField();
        jBtn_ir_papeletaPresidente = new javax.swing.JButton();
        jBtn_ir_votantes = new javax.swing.JButton();
        jLbl_reloj = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLbl_tituloRegistro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLbl_tituloRegistro.setForeground(new java.awt.Color(51, 0, 102));
        jLbl_tituloRegistro.setText("INGRESE SU NÚMERO DE CEDULA");
        jLbl_tituloRegistro.setName("jLbl_tituloRegistro"); // NOI18N

        jLbl_CI.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLbl_CI.setForeground(new java.awt.Color(102, 0, 102));
        jLbl_CI.setText("C.I.:");
        jLbl_CI.setName("jLbl_CI"); // NOI18N

        jTxFld_numCedula.setForeground(new java.awt.Color(102, 0, 102));
        jTxFld_numCedula.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 102)));
        jTxFld_numCedula.setName("jTxFld_numCedula"); // NOI18N
        jTxFld_numCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxFld_numCedulaKeyPressed(evt);
            }
        });

        jBtn_ir_papeletaPresidente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn_ir_papeletaPresidente.setForeground(new java.awt.Color(51, 0, 102));
        jBtn_ir_papeletaPresidente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/hg.JPG"))); // NOI18N
        jBtn_ir_papeletaPresidente.setText("REGISTRAR");
        jBtn_ir_papeletaPresidente.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 153)));
        jBtn_ir_papeletaPresidente.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jBtn_ir_papeletaPresidente.setName("jBtn_ir_papeletaPresidente"); // NOI18N
        jBtn_ir_papeletaPresidente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_ir_papeletaPresidenteMouseClicked(evt);
            }
        });
        jBtn_ir_papeletaPresidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ir_papeletaPresidenteActionPerformed(evt);
            }
        });

        jBtn_ir_votantes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn_ir_votantes.setForeground(new java.awt.Color(51, 0, 102));
        jBtn_ir_votantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/hvfk.JPG"))); // NOI18N
        jBtn_ir_votantes.setText("ATRAS");
        jBtn_ir_votantes.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 153)));
        jBtn_ir_votantes.setName("jBtn_ir_votantes"); // NOI18N
        jBtn_ir_votantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_ir_votantesMouseClicked(evt);
            }
        });

        jLbl_reloj.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLbl_reloj.setForeground(new java.awt.Color(255, 255, 255));
        jLbl_reloj.setName("jLbl_reloj"); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/muñeco.gif"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbl_reloj, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtn_ir_votantes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtn_ir_papeletaPresidente)))
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLbl_CI)
                        .addGap(18, 18, 18)
                        .addComponent(jTxFld_numCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLbl_tituloRegistro)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_CI)
                            .addComponent(jTxFld_numCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn_ir_votantes)
                            .addComponent(jBtn_ir_papeletaPresidente))
                        .addGap(45, 45, 45)
                        .addComponent(jLbl_reloj, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLbl_tituloRegistro)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtn_ir_papeletaPresidente, jBtn_ir_votantes});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_ir_votantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_ir_votantesMouseClicked
        try {
            // TODO add your handling code here:
            votantes ir = new votantes(); // crea objeto para ir a nueva ventana
            this.setVisible(false); //oculta la ventana actual
            ir.setVisible(true); // para que la ventana este siempre centrada
            ir.setLocationRelativeTo(null); // para que la ventana este siempre centrada
        } catch (FileNotFoundException ex) {
            Logger.getLogger(registro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(registro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtn_ir_votantesMouseClicked

    private void jBtn_ir_papeletaPresidenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_ir_papeletaPresidenteMouseClicked
        // TODO add your handling code here:
        String numcedula = jTxFld_numCedula.getText();//captura el numero de CI
        //codigo verificar que ingrese solo 10 digitos
        if (numcedula.length() < 10) {
            JOptionPane.showMessageDialog(null, "NUMERO DE CEDULA INCOMPLETO"," ERROR",0);
            jTxFld_numCedula.setText("");
        }
        if (numcedula.length() > 10) {
            JOptionPane.showMessageDialog(null, "HA EXCEDIDO EL NUMERO DE DIGITOS "," ERROR",0);
            jTxFld_numCedula.setText("");
        }
        // codigo para verificar si el numero de CI es valido
        if (numcedula.length() == 10) {
            Date now = new Date();
            long horasistema = now.getHours();
            horasistema = horasistema * 3600000;
            long minsistema = now.getMinutes();
            minsistema = minsistema * 60000;
            long sumasistema = horasistema + minsistema;
            ////////////////////////////////////
            File archivo = null;
            FileReader fr = null;
            BufferedReader br = null;
            File archivo1 = null;
            FileReader fr1 = null;
            BufferedReader br1 = null;
            try {
                // Apertura del fichero y creacion de BufferedReader para poder
                // hacer una lectura comoda (disponer del metodo readLine()).
                archivo = new File("suma_horas.txt");
                fr = new FileReader(archivo);
                br = new BufferedReader(fr);            
                // Lectura del fichero
                String linea="";
                while ((linea = br.readLine()) != null) {
                    StringTokenizer tok = new StringTokenizer(linea);//metodo para saltar espacios en blanco y tomar el siguiente dato del fichero
                    tok.nextToken();//hace un salto al siguiente dato del fichero
                    long linea1 = Long.parseLong(tok.nextToken().toString());
                    long linea2 = Long.parseLong(tok.nextToken().toString());
                    long r = sumasistema - linea1;
                    long resta = linea2 - sumasistema;
                        if (r >= 0) {
                            if (resta > 0) {
                      
                                    if (listo() == true) {
                                        if (existeRegistro() != false) {
                                            if (existeRegistro1() == false) {
                                                File entrada = new File("Compararcedula.txt");
                                                FileWriter fw = new FileWriter(entrada, true);
                                                PrintWriter pw = new PrintWriter(fw);
                                                pw.println(numcedula);
                                                pw.close();
                                                papeleta_presidente ir = new papeleta_presidente();// crea objeto para ir a nueva ventana
                                                this.setVisible(false);//oculta la ventana actual
                                                ir.setVisible(true);//muestra la nueva ventana
                                                ir.setLocationRelativeTo(null);// para que la ventana este siempre centrada

                                            } else {
                                                JOptionPane.showMessageDialog(null, "USTED YA VOTO", "* * *   ALTO   * * *", 0);
                                                votantes ir = new votantes();// crea objeto para ir a nueva ventana
                                                this.setVisible(false);//oculta la ventana actual
                                                ir.setVisible(true);//muestra la nueva ventana
                                                ir.setLocationRelativeTo(null);// para que la ventana este siempre centrada
                                            }
                                        } else {
                                            JOptionPane.showMessageDialog(null, "CEDULA INCORRECTA O NO ESTA EMPADRONADO", "           * * *   ERROR   * * *",0);
                                            jTxFld_numCedula.setText("");
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(null, "CEDULA INCORRECTA O NO ESTA EMPADRONADO", "* * *   ERROR   * * *", 0);
                                    }
                                
                            } else {
                                    JOptionPane.showMessageDialog(null, "TIEMPO AGOTADO");
                                    votantes ir = new votantes();// crea objeto para ir a nueva ventana
                                    this.setVisible(false);//oculta la ventana actual
                                    ir.setVisible(true);//muestra la nueva ventana
                                    ir.setLocationRelativeTo(null);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "SISTEMA NO HABILITADO");
                            votantes ir = new votantes();// crea objeto para ir a nueva ventana
                            this.setVisible(false);//oculta la ventana actual
                            ir.setVisible(true);//muestra la nueva ventana
                            ir.setLocationRelativeTo(null);// para que la ventana este siempre centrada
                        }                  
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jBtn_ir_papeletaPresidenteMouseClicked

    private void jTxFld_numCedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxFld_numCedulaKeyPressed
        // TODO add your handling code here:
         String str = jTxFld_numCedula.getText();//guarda cedula ingresada
        boolean resultado = str.startsWith("-");//ayuda para que ingrese numeros validos y no ingrese numeros negativos
        if (resultado == true) {//verifica si ingresa numeros negativos
            JOptionPane.showMessageDialog(null, "Ingrese una cantidad valida");//mensaje de aviso que el numero ingresado no es valido
            jTxFld_numCedula.setText("");//limpia casilla de ingreso de cedula
        }

        if (!jTxFld_numCedula.getText().equals("")) {//verifica si ingreso algun valor en el casillero de cedula
            try {
                int ci = Integer.parseInt(jTxFld_numCedula.getText());//convierte a entero la cedula de identidad ingresada
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Solo se pueden ingresar numeros");//mensaje si no se ingreso numeros
                jTxFld_numCedula.setText("");//limpia casilla de ingreso de cedula
            }
        }
    }//GEN-LAST:event_jTxFld_numCedulaKeyPressed

    private void jBtn_ir_papeletaPresidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ir_papeletaPresidenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_ir_papeletaPresidenteActionPerformed

    /**
     * @param args the command line arguments
     */
//     public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//
//                    new registro().setVisible(true); // clase principal
//
//            }
//        });
//    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_ir_papeletaPresidente;
    private javax.swing.JButton jBtn_ir_votantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbl_CI;
    private javax.swing.JLabel jLbl_reloj;
    private javax.swing.JLabel jLbl_tituloRegistro;
    private javax.swing.JTextField jTxFld_numCedula;
    // End of variables declaration//GEN-END:variables
}
