package proyecto_sev1;
import clases.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.util.*;
import java.awt.event.*;
public class votantes extends JFrameConFondo {
    /** Creates new form votantes */
    public votantes() throws FileNotFoundException, IOException {
        initComponents();
        setImagen("Recursos/alfaro.jpg");
        setLocationRelativeTo(null);// para que la ventana este siempre centrada
        Reloj modelo=new Reloj();//codigo para crear objeto de clase Reloj
                modelo.addObserver (new Observer()
                 {
                     public void update (Observable unObservable, Object dato)
                     {
                         jLbl_reloj.setText(""+dato);//codigo para mostrar reloj
                     }
                 });
                 //muestra hora de inicio y fin de sistema
                 mostrar_hora();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbl_titulo_SEV = new javax.swing.JLabel();
        jBtn_candidatoCorrea = new javax.swing.JButton();
        jBtn_candidatoGutierrez = new javax.swing.JButton();
        jBtn_candidatoMahuad = new javax.swing.JButton();
        jBtn_candidatoRoldos = new javax.swing.JButton();
        jLbl_candidatoCorrea = new javax.swing.JLabel();
        jLbl_candidatoGutierrez = new javax.swing.JLabel();
        jLbl_candidatoMahuad = new javax.swing.JLabel();
        jLbl_candidatoRoldos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtArea_informacionSEV = new javax.swing.JTextArea();
        jBtn_ir_registro = new javax.swing.JButton();
        jBtn_ir_informacionAyuda = new javax.swing.JButton();
        jBtn_ir_codigoAdmin = new javax.swing.JButton();
        jLbl_reloj = new javax.swing.JLabel();
        jLbl_Apertura = new javax.swing.JLabel();
        jLbl_Cierre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLbl_titulo_SEV.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLbl_titulo_SEV.setForeground(new java.awt.Color(51, 0, 102));
        jLbl_titulo_SEV.setText("SISTEMA ELECTRONICO DE VOTACIONES");
        jLbl_titulo_SEV.setName("jLbl_titulo_SEV"); // NOI18N

        jBtn_candidatoCorrea.setBackground(new java.awt.Color(0, 0, 0));
        jBtn_candidatoCorrea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/correa.JPG"))); // NOI18N
        jBtn_candidatoCorrea.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        jBtn_candidatoCorrea.setName("jBtn_candidatoCorrea"); // NOI18N
        jBtn_candidatoCorrea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_candidatoCorreaMouseClicked(evt);
            }
        });
        jBtn_candidatoCorrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_candidatoCorreaActionPerformed(evt);
            }
        });

        jBtn_candidatoGutierrez.setBackground(new java.awt.Color(0, 0, 0));
        jBtn_candidatoGutierrez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/lucio.JPG"))); // NOI18N
        jBtn_candidatoGutierrez.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        jBtn_candidatoGutierrez.setName("jBtn_candidatoGutierrez"); // NOI18N
        jBtn_candidatoGutierrez.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_candidatoGutierrezMouseClicked(evt);
            }
        });
        jBtn_candidatoGutierrez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_candidatoGutierrezActionPerformed(evt);
            }
        });

        jBtn_candidatoMahuad.setBackground(new java.awt.Color(0, 0, 0));
        jBtn_candidatoMahuad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/jamil.JPG"))); // NOI18N
        jBtn_candidatoMahuad.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        jBtn_candidatoMahuad.setName("jBtn_candidatoMahuad"); // NOI18N
        jBtn_candidatoMahuad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_candidatoMahuadMouseClicked(evt);
            }
        });

        jBtn_candidatoRoldos.setBackground(new java.awt.Color(0, 0, 0));
        jBtn_candidatoRoldos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/roldos.JPG"))); // NOI18N
        jBtn_candidatoRoldos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        jBtn_candidatoRoldos.setName("jBtn_candidatoRoldos"); // NOI18N
        jBtn_candidatoRoldos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_candidatoRoldosMouseClicked(evt);
            }
        });

        jLbl_candidatoCorrea.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLbl_candidatoCorrea.setForeground(new java.awt.Color(51, 0, 102));
        jLbl_candidatoCorrea.setText("Eco. Rafael Correa");
        jLbl_candidatoCorrea.setName("jLbl_candidatoCorrea"); // NOI18N

        jLbl_candidatoGutierrez.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLbl_candidatoGutierrez.setForeground(new java.awt.Color(51, 0, 102));
        jLbl_candidatoGutierrez.setText("Crnl. Lucio Gutierrez");
        jLbl_candidatoGutierrez.setName("jLbl_candidatoGutierrez"); // NOI18N

        jLbl_candidatoMahuad.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLbl_candidatoMahuad.setForeground(new java.awt.Color(51, 0, 102));
        jLbl_candidatoMahuad.setText("Dr. Jamil Mahuad");
        jLbl_candidatoMahuad.setName("jLbl_candidatoMahuad"); // NOI18N

        jLbl_candidatoRoldos.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLbl_candidatoRoldos.setForeground(new java.awt.Color(51, 0, 102));
        jLbl_candidatoRoldos.setText("Ab. Jaime Roldos");
        jLbl_candidatoRoldos.setName("jLbl_candidatoRoldos"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTxtArea_informacionSEV.setColumns(20);
        jTxtArea_informacionSEV.setEditable(false);
        jTxtArea_informacionSEV.setFont(new java.awt.Font("Monospaced", 1, 12));
        jTxtArea_informacionSEV.setForeground(new java.awt.Color(102, 0, 102));
        jTxtArea_informacionSEV.setRows(5);
        jTxtArea_informacionSEV.setText("\t\t\t\t\t\t \n\t\t\t\t\t\t     BIENVENIDOS\n\t\t\t\t\tAl sistema electrónico de votaciones\n\n\t\t\t\t\tPara mayor informacion haga click en \n\t\t\t\t\t\t     el botón ayuda\t"); // NOI18N
        jTxtArea_informacionSEV.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 0, 102)));
        jTxtArea_informacionSEV.setName("jTxtArea_informacionSEV"); // NOI18N
        jScrollPane1.setViewportView(jTxtArea_informacionSEV);

        jBtn_ir_registro.setFont(new java.awt.Font("Tahoma", 1, 12));
        jBtn_ir_registro.setForeground(new java.awt.Color(51, 0, 102));
        jBtn_ir_registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/votar.jpg"))); // NOI18N
        jBtn_ir_registro.setText(" VOTAR");
        jBtn_ir_registro.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 0, 102)));
        jBtn_ir_registro.setName("jBtn_ir_registro"); // NOI18N
        jBtn_ir_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_ir_registroMouseClicked(evt);
            }
        });

        jBtn_ir_informacionAyuda.setFont(new java.awt.Font("Tahoma", 1, 12));
        jBtn_ir_informacionAyuda.setForeground(new java.awt.Color(51, 0, 102));
        jBtn_ir_informacionAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/ayuda.jpg"))); // NOI18N
        jBtn_ir_informacionAyuda.setText("AYUDA");
        jBtn_ir_informacionAyuda.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 0, 102)));
        jBtn_ir_informacionAyuda.setName("jBtn_ir_informacionAyuda"); // NOI18N
        jBtn_ir_informacionAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_ir_informacionAyudaMouseClicked(evt);
            }
        });

        jBtn_ir_codigoAdmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn_ir_codigoAdmin.setForeground(new java.awt.Color(51, 0, 102));
        jBtn_ir_codigoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_sev1/Recursos/ico_salir.jpg"))); // NOI18N
        jBtn_ir_codigoAdmin.setText(" SALIR");
        jBtn_ir_codigoAdmin.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 0, 102)));
        jBtn_ir_codigoAdmin.setName("jBtn_ir_codigoAdmin"); // NOI18N
        jBtn_ir_codigoAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_ir_codigoAdminMouseClicked(evt);
            }
        });
        jBtn_ir_codigoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ir_codigoAdminActionPerformed(evt);
            }
        });

        jLbl_reloj.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLbl_reloj.setForeground(new java.awt.Color(51, 0, 102));
        jLbl_reloj.setName("jLbl_reloj"); // NOI18N

        jLbl_Apertura.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLbl_Apertura.setForeground(new java.awt.Color(153, 0, 0));
        jLbl_Apertura.setName("jLbl_Apertura"); // NOI18N

        jLbl_Cierre.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLbl_Cierre.setForeground(new java.awt.Color(153, 0, 0));
        jLbl_Cierre.setName("jLbl_Cierre"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLbl_Cierre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLbl_Apertura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(287, 287, 287))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtn_candidatoCorrea, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addGap(109, 109, 109))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLbl_candidatoCorrea)
                        .addGap(106, 106, 106)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLbl_candidatoGutierrez)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(jLbl_candidatoMahuad))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtn_candidatoGutierrez, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addGap(121, 121, 121)
                        .addComponent(jBtn_candidatoMahuad, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jBtn_candidatoRoldos, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLbl_candidatoRoldos)))
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtn_ir_registro)
                        .addGap(157, 157, 157)
                        .addComponent(jBtn_ir_informacionAyuda)
                        .addGap(170, 170, 170)
                        .addComponent(jBtn_ir_codigoAdmin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLbl_reloj, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addComponent(jLbl_titulo_SEV)
                .addGap(175, 175, 175))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtn_candidatoCorrea, jBtn_candidatoGutierrez, jBtn_candidatoMahuad, jBtn_candidatoRoldos});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtn_ir_codigoAdmin, jBtn_ir_informacionAyuda, jBtn_ir_registro});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLbl_titulo_SEV)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtn_candidatoRoldos)
                    .addComponent(jBtn_candidatoCorrea)
                    .addComponent(jBtn_candidatoGutierrez)
                    .addComponent(jBtn_candidatoMahuad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_candidatoCorrea)
                    .addComponent(jLbl_candidatoGutierrez)
                    .addComponent(jLbl_candidatoMahuad)
                    .addComponent(jLbl_candidatoRoldos))
                .addGap(45, 45, 45)
                .addComponent(jLbl_Apertura, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLbl_Cierre, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLbl_reloj, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_ir_registro)
                    .addComponent(jBtn_ir_informacionAyuda)
                    .addComponent(jBtn_ir_codigoAdmin))
                .addGap(23, 23, 23))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtn_candidatoCorrea, jBtn_candidatoGutierrez, jBtn_candidatoMahuad, jBtn_candidatoRoldos});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtn_ir_codigoAdmin, jBtn_ir_informacionAyuda, jBtn_ir_registro});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLbl_Apertura, jLbl_Cierre});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_candidatoGutierrezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_candidatoGutierrezActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_candidatoGutierrezActionPerformed

    private void jBtn_candidatoCorreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_candidatoCorreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_candidatoCorreaActionPerformed
    //metodo para  mostrar hor de inicio y fin
    private void mostrar_hora() throws FileNotFoundException, IOException
    {
            File archivo = null;
            FileReader fr = null;
            BufferedReader br = null;
            archivo = new File("suma_horas.txt");
            fr = new FileReader(archivo);
            br = new BufferedReader(fr);
            String linea;
            while ((linea = br.readLine()) != null) //guarda el contenido de cada linea de fichero hasta el final y guarda en linea
            {

                StringTokenizer tok = new StringTokenizer(linea);//metodo para saltar espacios en blanco y tomar el siguiente dato del fichero
                tok.nextToken();
                tok.nextToken();
                tok.nextToken();
                String hora_inicio = tok.nextToken().toString();//guarda codigo de empadronado
                String min_inicio = tok.nextToken().toString();//guarda codigo de empadronado
                String hora_fin = tok.nextToken().toString();//guarda codigo de empadronado
                String min_fin = tok.nextToken().toString();//guarda codigo de empadronado
                jLbl_Apertura.setText("HORA DE INICIO DEL SISTEMA:      "+hora_inicio+":"+min_inicio);
                jLbl_Cierre.setText("HORA DE CIERRE DEL SISTEMA:     "+hora_fin+":"+min_fin);
      }
    }
   
    private void jBtn_candidatoCorreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_candidatoCorreaMouseClicked
        // TODO add your handling code here:
        //metodo para informar datos de candidato
         jTxtArea_informacionSEV.setText("\n  Eco. RAFAEL CORREA\n\n  ESTUDIOS\n"+"  Realizó todos sus estudios primarios y secundarios en el colegio católico\n  San José - La Salle de la ciudad de Guayaquil" +
                ",  obtuvo una beca para estudiar en la\n  Universidad Católica de Santiago de Guayaquil, un instituto particular en Ecuador,\n  en el que finalmente se graduó de economista.\n\n" +
                "     PROPUESTAS\n" +
                "          1.Mantener la dolarización.\n" +
                "          2.Mantenimiento de carreteras.\n" +
                "          3.Combatir la delincuencia y la corrupción.\n");

    }//GEN-LAST:event_jBtn_candidatoCorreaMouseClicked

    private void jBtn_candidatoGutierrezMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_candidatoGutierrezMouseClicked
        // TODO add your handling code here:
        //metodo para informar datos de candidato
        jTxtArea_informacionSEV.setText("\n  Crnl. Lucio Gutierrez\n\n  ESTUDIOS\n"+"  Resolvió emprender la carrera militar, así que interrumpió su formación escolar en Tena y se inscribió\n  en el Colegio Militar Eloy Alfaro de Quito, donde terminó el bachillerato y en 1977 se graduó con el grado\n  de subteniente del arma de Caballería, posee los títulos de: ingeniero civil, licenciado en Administración,\n  diplomado en Alta Gerencia y diplomado en Liderazgo Estratégico, todo ello por la Escuela Politécnica\n  del Ejército (ESPE) de Quito.\n\n"+
               "     PROPUESTAS\n" +
                "          1. La lucha frontal e implacable, con características de cruzada, contra toda forma de\n             corrupción y fraude económicos cometidos por funcionarios públicos,\n             empresarios privados y financieros.\n" +
                "          2. Atención prioritaria, por delante de transformaciones como la privatización de los\n             sectores eléctrico y de telecomunicaciones.\n" +
                "          3. Combatir la delincuencia y la corrupción.\n");
    }//GEN-LAST:event_jBtn_candidatoGutierrezMouseClicked

    private void jBtn_candidatoMahuadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_candidatoMahuadMouseClicked
        // TODO add your handling code here:
        //metodo para informar datos de candidato
        jTxtArea_informacionSEV.setText("\n  Dr. Jamil Mahuad\n\n  ESTUDIOS\n"+"  La primaria la realizó con los Hermanos de las Escuelas Cristianas – La Salle. Secundaria\n  en el Colegio San Gabriel de Quito, de los PP. Jesuitas. Superior en la Pontificia\n  Universidad Católica del Ecuador, Quito. Se graduó de Doctor en Jurisprudencia y Abogado de los\n  Tribunales de la República. En la Universidad (John F. Kennedy) School of Goverment de\n  Harvard, Estados Unidos, obtuvo el Masterado en Administración Pública.\n\n"+
               "     PROPUESTAS\n" +
                "          1.Subir el bono.\n" +
                "          2.Crear fundación para ayuda a discapacitados.\n" +
                "          3.Medicina gratuita para menores de 5 años.\n");
    }//GEN-LAST:event_jBtn_candidatoMahuadMouseClicked

    private void jBtn_candidatoRoldosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_candidatoRoldosMouseClicked
        // TODO add your handling code here:
        //metodo para informar datos de candidato
        jTxtArea_informacionSEV.setText("\n  Ab. Jaime Roldos\n\n  ESTUDIOS\n"+"  Su educación secundaria cursó en el colegio Nacional Vicente Rocafuerte, egresó como el mejor Bachiller\n  Vicentino recibido este premio que otorga el plantel. Luego siguió Jurisprudencia y Ciencia Sociales\n  en la Universidad de Guayaquil, obteniendo el premio Contenta.\n\n"+
               "     PROPUESTAS\n" +
                "          1.Plan Nacional de Alfabetización.\n" +
                "          2.Combatir la desnutrición escolar.\n" +
                "          3.Obras hidroeléctricas nacionales.\n");
    }//GEN-LAST:event_jBtn_candidatoRoldosMouseClicked

    private void jBtn_ir_codigoAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_ir_codigoAdminMouseClicked
        // TODO add your handling code here:
        codigo_admin ir = new  codigo_admin ();// crea objeto para ir a nueva ventana
        this.setVisible(false);//oculta la ventana actual
        ir.setVisible(true);//muestra la nueva ventana
        ir.setLocationRelativeTo(null);// para que la ventana este siempre centrada
    }//GEN-LAST:event_jBtn_ir_codigoAdminMouseClicked

    private void jBtn_ir_informacionAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_ir_informacionAyudaMouseClicked
        // TODO add your handling code here:
        //metodo para informar datos de candidato
        jTxtArea_informacionSEV.setText("INDICACIONES: \n"+"1. Para ver la información de los candidatos haga click en la imagen del candidato que desee\n" +
                                     "2. Si desea registrar su voto haga click en VOTAR\n " +
                                     "   2.1. Se despliega una ventana para que ingrese su numero de cedula y haga click en ACEPTAR\n " +
                                     "   2.2. Escoja el candidato de su preferencia " ); // codigo para mostrar informacion de candidatos

    }//GEN-LAST:event_jBtn_ir_informacionAyudaMouseClicked

    private void jBtn_ir_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_ir_registroMouseClicked
        // TODO add your handling code here:
        registro ir = new  registro();// crea objeto para ir a nueva ventana
        this.setVisible(false);//oculta la ventana actual
        ir.setVisible(true);//muestra la nueva ventana
        ir.setLocationRelativeTo(null);// para que la ventana este siempre centrada
    }//GEN-LAST:event_jBtn_ir_registroMouseClicked

    private void jBtn_ir_codigoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ir_codigoAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_ir_codigoAdminActionPerformed

    /**
    * @param args the command line arguments
    */
//     public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new votantes().setVisible(true); // clase principal
//                } catch (FileNotFoundException ex) {
//                    Logger.getLogger(votantes.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (IOException ex) {
//                    Logger.getLogger(votantes.class.getName()).log(Level.SEVERE, null, ex);
//                }
//
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_candidatoCorrea;
    private javax.swing.JButton jBtn_candidatoGutierrez;
    private javax.swing.JButton jBtn_candidatoMahuad;
    private javax.swing.JButton jBtn_candidatoRoldos;
    private javax.swing.JButton jBtn_ir_codigoAdmin;
    private javax.swing.JButton jBtn_ir_informacionAyuda;
    private javax.swing.JButton jBtn_ir_registro;
    private javax.swing.JLabel jLbl_Apertura;
    private javax.swing.JLabel jLbl_Cierre;
    private javax.swing.JLabel jLbl_candidatoCorrea;
    private javax.swing.JLabel jLbl_candidatoGutierrez;
    private javax.swing.JLabel jLbl_candidatoMahuad;
    private javax.swing.JLabel jLbl_candidatoRoldos;
    private javax.swing.JLabel jLbl_reloj;
    private javax.swing.JLabel jLbl_titulo_SEV;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtArea_informacionSEV;
    // End of variables declaration//GEN-END:variables

}
